fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "globalbigbell@rambler.ru"
        sender_name: "globalbigbell@rambler.ru"
    registration:
        confirmation:
            enabled: false
        form:
            type: App\Form\RegistrationType
