fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "admin@bigbell.net"
        sender_name: "admin@bigbell.net"
    registration:
        confirmation:
            enabled: true
