# config/routes.yaml
app_index:
    path: /
    controller: App\Controller\IndexController::index
app_index_about:
    path: /about
    controller: App\Controller\IndexController::about
app_index_howto:
    path: /howto
    controller: App\Controller\IndexController::howto
app_index_agreement:
    path: /agreement
    controller: App\Controller\IndexController::agreement
app_admin:
    path: /admin/
    controller: App\Controller\AdminController::index
