# config/routes.yaml
app_index:
    path: /
    controller: App\Controller\IndexController::index
app_index_about:
    path: /about
    controller: App\Controller\IndexController::about
app_admin:
    path: /admin/
    controller: App\Controller\AdminController::index
