# config/routes.yaml
app_index:
    path: /
    controller: App\Controller\IndexController::index
app_index_about:
    path: /about
    controller: App\Controller\IndexController::about
app_index_howto:
    path: /howto
    controller: App\Controller\IndexController::howto
app_index_agreement:
    path: /agreement
    controller: App\Controller\IndexController::agreement
app_admin:
    path: /admin/
    controller: App\Controller\AdminController::index
app_admin_withdraw:
    path: /admin/withdraw
    controller: App\Controller\AdminController::withdraw
app_admin_ajax_invest:
    path: /admin/ajax/invest
    controller: App\Controller\AdminController::ajaxInvest
    methods:  [POST]
app_payeer_index:
    path: /payeer/
    controller: App\Controller\PayeerController::index
app_payeer_success:
    path: /payeer/success
    controller: App\Controller\PayeerController::success
app_payeer_fail:
    path: /payeer/fail
    controller: App\Controller\PayeerController::fail
app_payeer_status:
    path: /payeer/status
    controller: App\Controller\PayeerController::status
app_admin_verify:
    path: /admin/verify
    controller: App\Controller\AdminController::verify
