# config/routes.yaml
app_index:
    path: /
    controller: App\Controller\IndexController::index
app_index_about:
    path: /about
    controller: App\Controller\IndexController::about
app_index_howto:
    path: /howto
    controller: App\Controller\IndexController::howto
app_index_agreement:
    path: /agreement
    controller: App\Controller\IndexController::agreement
app_admin:
    path: /admin/
    controller: App\Controller\AdminController::index
app_admin_add:
    path: /admin/add/
    controller: App\Controller\AdminController::add
app_admin_add_confirm:
    path: /admin/add/confirm/
    controller: App\Controller\AdminController::addConfirm
    methods:  [POST]
app_admin_ajax_invest:
    path: /admin/ajax/invest
    controller: App\Controller\AdminController::ajaxInvest
    methods:  [POST]
app_admin_verify:
    path: /admin/verify
    controller: App\Controller\AdminController::verify
app_training:
    path: /training
    controller: App\Controller\IndexController::training
app_admin_withdraw:
    path: /admin/withdraw
    controller: App\Controller\AdminController::withdraw
app_admin_withdraw_confirm:
    path: /admin/withdraw/confirm
    controller: App\Controller\AdminController::withdrawConfirm
app_admin_training:
    path: /admin/training
    controller: App\Controller\AdminController::training
app_index_contactform:
    path: /contactform
    controller: App\Controller\IndexController::contactform
app_index_payeer_success:
    path: /payeer/success
    controller: App\Controller\AdminController::payeer
app_index_payeer_fail:
    path: /payeer/fail
    controller: App\Controller\AdminController::payeer
app_index_payeer_status:
    path: /payeer/status
    controller: App\Controller\AdminController::payeer
app_services_thailandPropertyInvestments:
    path: /services/thailand/property-investments
    controller: App\Controller\ServicesController::thailandPropertyInvestments
app_services_ipo:
    path: /services/ipo
    controller: App\Controller\ServicesController::ipo
app_services_robotic_trading:
    path: /services/robotic-trading
    controller: App\Controller\ServicesController::roboticTrading
app_services_individual_management:
    path: /services/individual-management
    controller: App\Controller\ServicesController::individualManagement
app_services_cars:
    path: /services/cars
    controller: App\Controller\ServicesController::cars



